/* DISPLAY SIZE / SIDEBAR */
export const DISPLAY_SIZE_CHANGED = 'DISPLAY_SIZE_CHANGED';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

/* AUTHENTICATION */
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_ACCOUNT_MESSAGE = 'USER_ACCOUNT_MESSAGE';
export const CLEAR_USER_ORDERS = 'CLEAR_USER_ORDERS';

/* PRODUCTS / SINGLE PRODUCT*/
export const FETCH_PRODUCTS_FROM_SERVER = 'FETCH_PRODUCTS_FROM_SERVER'
export const FETCH_SINGLE_PRODUCT_FROM_SERVER = 'FETCH_SINGLE_PRODUCT_FROM_SERVER'


/* ORDERS */
export const ORDER_PRODUCT_TO_CART = 'ORDER_PRODUCT_TO_CART';
export const ORDER_PRODUCT_TO_SESSION = 'ORDER_PRODUCT_TO_SESSION';
export const FETCH_USER_ORDERS_FROM_SERVER = 'FETCH_ORDERS_FROM_SERVER';
export const FETCH_USER_ORDER_HISTORY_FROM_SERVER = 'FETCH_USER_ORDER_HISTORY_FROM_SERVER';
export const FETCH_USER_WISHLIST_FROM_SERVER = 'FETCH_USER_WISHLIST_FROM_SERVER';
export const ORDER_SELECTED_FROM_CART = 'ORDER_SELECTED_FROM_CART';

/* INVOICE */
export const UPDATE_INVOICE = 'UPDATE_INVOICE';

/* ADMIN */
export const ADMIN_FETCH_ORDERS_FROM_SERVER = 'ADMIN_FETCH_ORDERS_FROM_SERVER';
export const ADMIN_FETCH_INVOICES_FROM_SERVER = 'ADMIN_FETCH_INVOICES_FROM_SERVER';
export const ADMIN_ADD_FILES_TO_UPLOAD = 'ADMIN_ADD_FILES_TO_UPLOAD';
export const ADMIN_UPLOAD_FILES_TO_SERVER = 'ADMIN_UPLOAD_FILES_TO_SERVER';
